Opdracht: Doorrekenen van een neuraal netwerk.

# Doorrekenen van een neuraal netwerk

In deze opdracht lees ik een netwerk in vanuit een json-bestand en dit netwerk word dan gebruikt om matrices te maken. Met die matrices als input word een output berekent.

Numpy en json worden geimporteerd en een variable voor de json filenaam word aangemaakt.

In [135]:
import numpy as np
import json

file2 = "example-2layer.json"

Om de informatie van de jsonfile te kunnen inlezen zodat de matrice gemaakt kan worden, wordt de informatie in de Jsonfile omgezet naar een dictionary.

In [136]:
def jsonToDict(filename):
#   file word geopent gelezen en in een dict gezet, een dict word returnd
    file = open(filename)
    j = file.read()
    dJ = json.loads(j)
    file.close()
    return dJ

Numpy heeft een specifieke notatie nodig om een matrix aan te maken. De functie hieronder maakt gebruik van een dictionary, met de informatie voor de matrix, om die om te zetten naar een string die numpy kan gebruiken om een matrix aan te maken. Zodra de matrix is aangemaakt word die returnd.

In [141]:
def dictToMatrix(jD):
    # de dict word uitgelezen en een matrix word returnd
    mString = ""
    size_out = int(jD["size_out"])
    size_in = int(jD["size_in"])
    
#   met behulp van size_out en size_in word er door de dict geloopt om de juiste aantal waardes te krijgen
    i = 1
    while i < size_in+1:
        j = 1
        while j < size_out+1:
#           als er een waarde is word die in de matrix opgeslagen
            try:
                n = jD["weights"][str(i)][str(j)]
#           als er geen waarde is wordt er een random getal tussen -1 en 1 opgeslagen
            except:
                n = np.random.randint(-1, high=1, dtype=int)
            mString += str(n) + " "
            j += 1
        mString += ";"
        i += 1
    mString = mString[:-1]
    
#   met gebruik van de aangemaakte string word met numpy een matrix aangemaakt 
    matrix = np.matrix(mString)
    return matrix

In de volgende functie wordt de matrixvermenigvuldiging uitgevoerd.

Matrixvermenigvuldiging van matrix1 met matrix2 kan alleen als het aantal kolommen van matrix1 gelijk is aan het aantal rijen van matrix2. Daarom als matrix1 M x N is, moet matrix2 N x P zijn.

In [142]:
def matrixMultiplication(matrixA, matrixB):
#       Een lege matrixC met de correcte groote word aangemaakt
        matrixC = np.zeros((matrixA.shape[0],matrixB.shape[1]))
    
#       controle of de kolommen van MatrixA gelijk zijn aan de rijen van matrixB                              
        if (matrixA.shape[1] != matrixB.shape[0]):
            print("Length n and length n are not the same.")
            return matrixC
#       Er wordt aan de hand van de kolommen en rijen van matrixA en matrixB geloopt om matrixC in te vullen
        for i in range(matrixA.shape[0]):
            for j in range(matrixB.shape[1]):
#               De som word doorlopen en de uitkomst word op de juiste plek in matrixC gezet
                for k in range(matrixA.shape[1]):
                    matrixC[i,j] = matrixC[i,j] + (matrixA[i,k] * matrixB[k,j])
#       De nieuwe matrixC word returnd
        return  matrixC

Met behulp van de functie dictToMatrix worden nu twee matrixen worden gemaakt, matrix1 en matrix2. 

In [143]:
matrix1 = dictToMatrix(matrixData["layer1"])
matrix2 = dictToMatrix(matrixData["layer2"])

De jsonfile word ingelezen en word als dict opgeslagen

In [144]:
matrixData = jsonToDict(file2)

Met behulp van de functie matrixMultiplication word met de twee matricen als input een output gegeven en geprint.

In [145]:
print(matrixMultiplication(matrix1, matrix2))

[[ 0.48 -0.29]
 [ 0.7   0.43]
 [-0.25 -0.12]
 [ 0.17 -0.42]
 [-0.88  0.26]]


Ter controle gebruik ik numpy om de matrixvermenigvuldiging te doen. Die zou het zelfde resultaat moeten geven als mijn functie.

In [146]:
print(np.dot(matrix1,matrix2))

[[ 0.48 -0.29]
 [ 0.7   0.43]
 [-0.25 -0.12]
 [ 0.17 -0.42]
 [-0.88  0.26]]


Hieronder nogmaals de volledige code:

In [134]:
import numpy as np
import json

# variable voor json filenaam word aangemaakt
file2 = "example-2layer.json"

def jsonToDict(filename):
#   file word geopent gelezen en in een dict gezet, de dict word gereturnt
    file = open(filename)
    j = file.read()
    dJ = json.loads(j)
    file.close()
    return dJ

def dictToMatrix(jD):
    # de dict word uitgelezen en een matrix word gereturnt
    mString = ""
    size_out = int(jD["size_out"])
    size_in = int(jD["size_in"])
    
#   met behulp van size_out en size_in word er door de dict geloopt om de juiste aantal waardes te krijgen
    i = 1
    while i < size_in+1:
        j = 1
        while j < size_out+1:
#           als er een waarde is word die in de matrix opgeslagen
            try:
                n = jD["weights"][str(i)][str(j)]
#           als er geen waarde is wordt er een random getal tussen -1 en 1 opgeslagen
            except:
                n = np.random.randint(-1, high=1, dtype=int)
            mString += str(n) + " "
            j += 1
        mString += ";"
        i += 1
    mString = mString[:-1]
    
#   met gebruik van de aangemaakte string word met numpy een matrix aangemaakt 
    matrix = np.matrix(mString)
    return matrix

def matrixMultiplication(matrixA, matrixB):
        matrixC = np.zeros((matrixA.shape[0],matrixB.shape[1]))
                              
        if (matrixA.shape[1] != matrixB.shape[0]):
            print("Length k and length n are not the same.")
            return matrixC

        for i in range(matrixA.shape[0]):
            for j in range(matrixB.shape[1]):
                for k in range(matrixA.shape[1]):
                    matrixC[i,j] = matrixC[i,j] + (matrixA[i,k] * matrixB[k,j])
        return  matrixC

# de jsonfile word ingelezen en word als dict opgeslagen
matrixData = jsonToDict(file2)

# de twee matrixen worden aangemaakt
matrix1 = dictToMatrix(matrixData["layer1"])
matrix2 = dictToMatrix(matrixData["layer2"])

# de output van de matrix multiplication van de twee matrixen word geprint
print(matrixMultiplication(matrix1, matrix2))
print()
# controle met numpy
print(np.dot(matrix1,matrix2))


[[ 0.38  0.01]
 [ 0.7   0.43]
 [ 0.25  0.08]
 [ 0.17 -0.42]
 [-0.88  0.26]]

[[ 0.38  0.01]
 [ 0.7   0.43]
 [ 0.25  0.08]
 [ 0.17 -0.42]
 [-0.88  0.26]]
