## Oplossen van magische vierkanten met alleen integers

Bron: https://pdfs.semanticscholar.org/e5a8/46cf1434bc1c9942fd97ce10f71d0c73b4c8.pdf

Om een magisch vierkant goed te kunnen oplossen moeten we er naar kijken als een stelsel vergelijken in matrix vorm. 
$A \vec{x} = \vec{b}$

Magische vierkant zijn vierkanten bestaande uit getallen waarbij de sommen van de getallen op de rijen, kolommen en diagonalen allemaal hetzelfde is, bijvoorbeeld:

\begin{array}{|c|c|c|}
\hline
8 & 3 & 4 \\ \hline
1 & 5 & 9 \\ \hline
6 & 7 & 2 \\ \hline
\end{array}

Hierbij is de som van alle rijen, kolommen en diagonalen gelijk aan 15.

Om uit te leggen hoe je een magische vierkant kan oplossen neem ik het magische vierkant hierboven en laat de meeste waarden weg. Ook gaan we er hier vanuit dat we niet weten dat de som van alle rijen, kolommen en diagonalen 15 is, die word vanaf nu y. 

\begin{array}{|c|c|c|}
\hline
8 & ~~ & ~~ \\ \hline
~~ & ~~ & 9 \\ \hline
~~ & ~~ & 2 \\ \hline
\end{array}

Eerst gaan we alles in een formule zetten, waarbij de pozities van de in matrix worden aangeduid met X1 tot en met X9 (dit kan varieren met de grote van het magische vierkant).
in het geval van het bovenstaande magische vierkant is $X1 = 8$, $X6 = 9$ en $X9 = 2$.

De vergelijkingen zijn gemaakt aan de hand van de al eerder genoemde formule $A \vec{x} = \vec{b}$.

Je moet de vergelijkingen dan ook eigenlijk zien niet als: $$8 + X2 + X3 = y$$ herschreven als: $$X2 + X3 -y = -8$$
Maar als:
$$1*8 + 1*X2 + 1*X3 = 0*X4 + 0*X5 + 0*X6 + 0*X7 + 0*X8 + 0*X9 = y$$ 

herschreven als:
$$0*X1 + 1*X2 + 1*X3 + 0*X4 + 0*X5 + 0*X6 + 0*X7 + 0*X8 + 0*X9 + 1*-y = -8$$

Dit kan je ook duidelijk terug zien als alle vergelijkingen in matrix row-echelon vorm zijn opgeschreven.

We kunnen nu de volgende acht vergelijkingen maken:

Voor de rijen:
$$8 + X2 + X3 = y$$
$$X4 + X5 +  9 = y$$
$$X7 + X8 +  2 = y$$

Voor de kolommen:
$$8 + X4 + X7 = y$$
$$X2 + X5 + X8 = y$$
$$X3 +  9 +  2 = y$$

Voor de diagonalen:
$$8 + X5 +  2 = y$$
$$X7 + X5 + X3 = y$$

Herschreven:
Voor de rijen:
$$X2 + X3 -y = -8$$
$$X4 + X5 -y = -9$$
$$X7 + X8 -y = -2$$

Voor de kolommen:
$$X4 + X7 -y = -8$$
$$X2 + X5 + X8 -y = 0$$
$$X3 -y = -11$$

Voor de diagonalen:
$$X5 -y = -10$$
$$X7 + X5 + X3 -y = 0$$

Nadat we de vergelijking hebben gemaakt en herschreven kunnen we de in matrix row-echelon vorm opschrijven, daarin zetten we ook de vergelijkingen voor de varibelen die we al gegeven hebben. Ook kunnen we de vergelijking $3*X5 -y = 0$ er in zetten omdat het middelste vak keer drie ook altijd de juist som geeft. Nu kan het magische vierkant worden opgelost.




$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 0 & -1 & -2\\
0 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & 0 & -1 & -8\\
0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & -1 &  0\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
0 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & -1 &  0\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 3 & 0 & 0 & 0 & 0 & -1 &  0\\
\end{array}\right]$$

Nu alles in matrix row-echelon vorm is opgeschreven gaan we eerst de rijen op een andere volgorde zetten om alles efficiënter te kunnen berekenen.

$\\R5 \rightarrow R2
\\R8 \rightarrow R3 
\\R2 \rightarrow R4
\\R7 \rightarrow R5
\\R4 \rightarrow R7
\\R3 \rightarrow R8$

$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & -1 &  0\\
0 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & -1 &  0\\
0 & 0 & 0 & 1 & 1 & 0 & 0 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & 0 & -1 & -8\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 0 & -1 & -2\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 3 & 0 & 0 & 0 & 0 & -1 &  0\\
\end{array}\right]$$

Nu de rijen op een ander volgorde zijn gezet is het al een stuk duidelijker. We gaan verder met row operations tot er maar éém 1 in een rij is en er onder elke 1 geen andere 1 staat.

$R4 - R5 \rightarrow R4$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & -1 &  0\\
0 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & -1 &  0\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & 0 & -1 & -8\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 0 & -1 & -2\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 3 & 0 & 0 & 0 & 0 & -1 &  0\\
\end{array}\right]$$

$R7 - R4 \rightarrow R7$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & -1 &  0\\
0 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & -1 &  0\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 0 & -1 & -2\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 3 & 0 & 0 & 0 & 0 & -1 &  0\\
\end{array}\right]$$

$R8 - R7 \rightarrow R8$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & -1 &  0\\
0 & 0 & 1 & 0 & 1 & 0 & 1 & 0 & 0 & -1 &  0\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 3 & 0 & 0 & 0 & 0 & -1 &  0\\
\end{array}\right]$$

$R3 - R5 \rightarrow R3$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & -1 &  0\\
0 & 0 & 1 & 0 & 0 & 0 & 1 & 0 & 0 &  0 & 10\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 3 & 0 & 0 & 0 & 0 & -1 &  0\\
\end{array}\right]$$

$R10 - R5 \rightarrow R10$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & -1 &  0\\
0 & 0 & 1 & 0 & 0 & 0 & 1 & 0 & 0 &  0 & 10\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 2 & 0 & 0 & 0 & 0 &  0 & 10\\
\end{array}\right]$$

$R10 / 2 \rightarrow R10$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & -1 &  0\\
0 & 0 & 1 & 0 & 0 & 0 & 1 & 0 & 0 &  0 & 10\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  5\\
\end{array}\right]$$

$R5 \leftrightarrow R10$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 1 & 0 & 0 & 1 & 0 & -1 &  0\\
0 & 0 & 1 & 0 & 0 & 0 & 1 & 0 & 0 &  0 & 10\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  5\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
\end{array}\right]$$

$R2 - R8 \rightarrow R2$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -7\\
0 & 0 & 1 & 0 & 0 & 0 & 1 & 0 & 0 &  0 & 10\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  5\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
\end{array}\right]$$

$R2 - R10 \rightarrow R2$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  3\\
0 & 0 & 1 & 0 & 0 & 0 & 1 & 0 & 0 &  0 & 10\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  5\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
\end{array}\right]$$

$R3 - R7 \rightarrow R3$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  3\\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 &  1 & 19\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  5\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
\end{array}\right]$$

$R3 + R10 \rightarrow R3$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  3\\
0 & 0 & 1 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  5\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & -1 & -10\\
\end{array}\right]$$

$R10 - R5 \rightarrow R10$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  3\\
0 & 0 & 1 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  5\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & -15\\
\end{array}\right]$$

$R3 - R5 \rightarrow R3$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  3\\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  4\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  5\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & -1 & -9\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & -15\\
\end{array}\right]$$

$R7 - R10 \rightarrow R7$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  3\\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  4\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  5\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 &  0 &  6\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & -15\\
\end{array}\right]$$

$R10 * R10 \rightarrow R10$
$$\left[\begin{array}{@{}rrrrrrrrrr|c@{}}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  8\\
0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  3\\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 & 0 &  0 &  4\\
0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 &  0 &  1\\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 & 0 &  0 &  5\\
0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 &  0 &  9\\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 &  0 &  6\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 &  0 &  7\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 &  0 &  2\\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 &  1 & 15\\
\end{array}\right]$$

Nu achter en onder elke 1 alleen maar nullen staan kunnen we kijken waar de X1 tot en met X9 en de y voor staan en hebben we het migische vierkant opgelost.


$$\begin{array}{|c|c|c|}
\hline
X1 = 8 & X2 = 3 & X3 = 4 \\ \hline
X4 = 1 & X5 = 5 & X6 = 9 \\ \hline
X7 = 6 & X8 = 7 &X9 = 2 \\ \hline
\end{array}$$

#### oplossen van 3x3 magische vierkanten met drie getallen gegeven in Python gebruik makend van numpy.

De code om een magisch vierkant op te lossen met numpy.

Note: de code werkt niet want ik heb een error die me niet lukt om op te lossen. De code is verder wl correct en ik laat ook zien hoe ik het magische vierkant word opglost.

In [23]:
import numpy as np

magicSq1 = [[8,0,0],[0,0,9],[0,0,2]]
magicSq2 = [[5,0,0],[0,0,4],[0,0,6]]

def hor_loop(magcsq):
    aMatrix = []
    bArray = []
    # horizontaal naar row echolon
    for i in range(0, 3):
        row = []
        totaal = 0
        # loop door de matrix
        for j in range(0, 3):
            for k in range(0, 3):
                if i == j:
                    totaal += magcsq[j][k]
                    if magcsq[j][k] == 0:
                        row.append(1)
                    else:
                        row.append(0)
                else:
                    row.append(0)
        row.append(-1)
        aMatrix.append(row)
        bArray.append(0 - totaal)
    info = [aMatrix, bArray]
    return info


def ver_loop(magcsq):
    aMatrix = []
    bArray = []
    # verticaal naar row echolon
    for i in range(0, 3):
        row = []
        totaal = 0
        # loop door de matrix
        for j in range(0, 3):
            for k in range(0, 3):
                if i == k:
                    totaal += magcsq[j][k]
                    if magcsq[j][k] == 0:
                        row.append(1)
                    else:
                        row.append(0)
                else:
                    row.append(0)
        row.append(-1)
        aMatrix.append(row)
        bArray.append(0 - totaal)
    info = [aMatrix, bArray]
    return info


def digLR_loop(magcsq):
    aMatrix = []
    bArray = []
    # diagonaal LR naar row echolon
    row = []
    totaal = 0
    # loop door de matrix
    for j in range(0, 3):
        for k in range(0, 3):
            if j == k:
                totaal += magcsq[j][k]
                if magcsq[j][k] == 0:
                    row.append(1)
                else:
                    row.append(0)
            else:
                row.append(0)
    row.append(-1)
    aMatrix.append(row)
    bArray.append(0 - totaal)
    info = [aMatrix, bArray]
    return info


def digRL_loop(magcsq):
    # diagonaal RL naar row echolon
    aMatrix = []
    bArray = []
    row = []
    totaal = 0
    counter = 2
    # loop door de matrix
    for j in range(0, 3):
        for k in range(0, 3):
            if k == counter:
                totaal += magcsq[j][counter]
                if magcsq[j][counter] == 0:
                    row.append(1)
                else:
                    row.append(0)
            else:
                row.append(0)
        counter -= 1
    row.append(-1)
    aMatrix.append(row)
    bArray.append(0 - totaal)
    info = [aMatrix, bArray]
    return info

def get_matrix_array(magcsq):
    matrix = []
    array = []
    row = [0, 0, 0, 0, 3, 0, 0, 0, 0, -1]
    hor = hor_loop(magcsq)
    ver = ver_loop(magcsq)
    digLR = digLR_loop(magcsq)
    digRL = digRL_loop(magcsq)

    for i in range(0, 3):
        matrix.append(hor[0][i])
        array.append([hor[1][i]])
    for i in range(0, 3):
        matrix.append(ver[0][i])
        array.append([ver[1][i]])
    matrix.append(digLR[0][0])
    array.append([digLR[1][0]])
    matrix.append(digRL[0][0])
    array.append([digRL[1][0]])
    matrix.append(row)
    matrix.append(row)
    array.append([0])
    array.append([0])
    infoList = [matrix, array]
    return infoList


infoList = get_matrix_array(magicSq1)

A = infoList[0]
b = infoList[1]

print(np.matrix(A))
print(np.matrix(b))

# inverse of A
invA = np.linalg.inv(A)
# som A en b voor x:
x = A * b

print(np.matrix(x))


[[ 0  1  1  0  0  0  0  0  0 -1]
 [ 0  0  0  1  1  0  0  0  0 -1]
 [ 0  0  0  0  0  0  1  1  0 -1]
 [ 0  0  0  1  0  0  1  0  0 -1]
 [ 0  1  0  0  1  0  0  1  0 -1]
 [ 0  0  1  0  0  0  0  0  0 -1]
 [ 0  0  0  0  1  0  0  0  0 -1]
 [ 0  0  1  0  1  0  1  0  0 -1]
 [ 0  0  0  0  3  0  0  0  0 -1]
 [ 0  0  0  0  3  0  0  0  0 -1]]
[[ -8]
 [ -9]
 [ -2]
 [ -8]
 [  0]
 [-11]
 [-10]
 [  0]
 [  0]
 [  0]]


LinAlgError: Singular matrix